# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billetera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(max_length=50, unique=True)),
                ('porcentaje_retiro', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cantidad', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
        ),
    ]
