# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billeteras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billetera',
            name='cantidad',
            field=models.DecimalField(decimal_places=5, max_digits=13),
        ),
    ]
